# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RTSPView', :git => 'https://github.com/ezlo-maxv/RTSPView.git'
  # Pods for Example

end
